language: node_js
node_js:
- '5'
- '4'

install:
- npm install

script:
- npm test
- npm run build

deploy:
  provider: npm
  email: "erfangc@gmail.com"
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
